### ISSUE TITLE
Parser doesn't allow for most import/export syntax

### ISSUE THREAD

**Issue by TodePond** [l2wilson94/Frogasaurus#8]
eg: `export default`
eg: `export function`
eg: `import foo from`
eg: `*`
eg: `default`

The Plan:
- [x] Shoddy bare-minimum parser #1 
- [x] Make Frogasaurus with Frogasaurus #6 
- [ ] Re-make MotherTode https://github.com/TodePond/MotherTode/issues/21
- [ ] Make a new Frogasaurus parser with MotherTode (this issue)
